### ISSUE TITLE
After excuting convert_lables.py, the generated pngs are all black

### ISSUE THREAD

**Issue by XCRobert** [Cloveryww/make-augmented-PascalVOC-semantic-segmentation-dataset-tool#1]
Something may wrong with your code

**Comment by Cloveryww** [comment]
Sorry to see your issue so late, maybe the pngs is not all black, but the color is hard to distinguish with naked eyes, if any other problem, welcome your response.

**Comment by Alice-Shen** [comment]
sorry to bother you, I got the error when i run convert_labels.py.
This is the error message:
`Traceback (most recent call last):
  File "convert_labels.py", line 88, in <module>
    main()
  File "convert_labels.py", line 60, in main
    img = convert_from_color_segmentation(img)
  File "convert_labels.py", line 37, in convert_from_color_segmentation
    m = np.all(arr_3d == np.array(c).reshape(1, 1, 3), axis=2)
  File "<__array_function__ internals>", line 6, in all
  File "/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2411, in all
    return _wrapreduction(a, np.logical_and, 'all', axis, None, out, keepdims=keepdims)
  File "/usr/local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
numpy.AxisError: axis 2 is out of bounds for array of dimension 0 `
